name: funds-explorer-scraper
services:
    api:
        build: ../api
        env_file:
        -   .api.env
        ports:
        -   ${API_SERVER_PORT}:80
    web:
        build: ../web
        env_file:
        -   .web.env
        ports:
        -   ${WEB_SERVER_PORT}:80
