name: funds-explorer-scraper
services:
  api:
    build: ../api
    env_file:
    -   .env.api
    ports:
    -   ${API_SERVER_PORT}:80
  web:
    build: ../web
    env_file:
    -   .env.web
    ports:
    -   ${WEB_SERVER_PORT}:80
